services:
  db:
    image: postgres:16
    container_name: trainingapp-db
    environment:
      POSTGRES_USER: trainingapp
      POSTGRES_PASSWORD: trainingapp_pass
      POSTGRES_DB: trainingapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: